export const PATHS = {
  home: "/",
  login: "/login",
  register: "/register",
  verifyOtp: "/auth/verify-otp",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  profile: "/profile",
  listings: "/listings",
  cart: "/cart",
  wishlist: "/wishlist",
  sellerProperties: "/seller/properties",
  sellerPropertyCreate: "/seller/properties/create",
  property: (id: string) => `/properties/${id}`,
} as const;
